%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushConsumer
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHCONSUMER_HRL).
-define(COSEVENTCOMM_PUSHCONSUMER_HRL, true).




-endif.


