%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ConsumerAdmin
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


