%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cosEventApp
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTAPP_HRL).
-define(OE_COSEVENTAPP_HRL, true).




-endif.


