%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertyNamesIterator
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYNAMESITERATOR_HRL).
-define(COSPROPERTYSERVICE_PROPERTYNAMESITERATOR_HRL, true).




-endif.


