%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosProperty
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSPROPERTY_HRL).
-define(OE_COSPROPERTY_HRL, true).




-endif.


