%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventDomainAdmin_ConnectionNotFound
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventDomainAdmin_ConnectionNotFound').
-ic_compiled("4_2_23").


-include("CosEventDomainAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventDomainAdmin/ConnectionNotFound:1.0",
                   "ConnectionNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventDomainAdmin/ConnectionNotFound:1.0".

%% returns name
name() -> "CosEventDomainAdmin_ConnectionNotFound".



