%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_VirtualFileSystem
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL).
-define(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL, true).




-endif.


