%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_SynchronizationUnavailable
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_SynchronizationUnavailable').
-ic_compiled("4_2_23").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0",
                   "SynchronizationUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0".

%% returns name
name() -> "CosTransactions_SynchronizationUnavailable".



