%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PullConsumer
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PULLCONSUMER_HRL).
-define(COSNOTIFYCOMM_PULLCONSUMER_HRL, true).




-endif.


