%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_FilterAdmin
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_FILTERADMIN_HRL).
-define(COSNOTIFYFILTER_FILTERADMIN_HRL, true).




-endif.


