%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyComm
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYCOMM_HRL).
-define(OE_COSNOTIFYCOMM_HRL, true).




-endif.


