%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ConnectionAlreadyInactive
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ConnectionAlreadyInactive').
-ic_compiled("4_2_23").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyInactive:1.0",
                   "ConnectionAlreadyInactive",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyInactive:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ConnectionAlreadyInactive".



