%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventDomainAdmin
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTDOMAINADMIN_HRL).
-define(OE_COSEVENTDOMAINADMIN_HRL, true).




-endif.


