%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventHandler
%% Source: /build/buildd/erlang-13.b.3-dfsg/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.23
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTHANDLER_HRL).
-define(COSTIMEREVENT_TIMEREVENTHANDLER_HRL, true).




-endif.


